apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-homework-4-kibana
  namespace: go
  labels:
    app: go-homework-4-kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-homework-4-kibana
  template:
    metadata:
      name: go-homework-4-kibana
      labels:
        app: go-homework-4-kibana
    spec:
      containers:
        - name: go-homework-4-kibana
          image: kibana:8.14.3
          imagePullPolicy: Always

      imagePullSecrets:
        - name: github-container-registry

      restartPolicy: Always
      