apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-homework-3-core
  namespace: go
  labels:
    app: go-homework-3-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-homework-3-core
  template:
    metadata:
      name: go-homework-3-core
      labels:
        app: go-homework-3-core
    spec:
      containers:
        - name: go-homework-3-go
          image: ghcr.io/umu-art/go-homework-3-core:master
          imagePullPolicy: Always

      imagePullSecrets:
        - name: github-container-registry

      restartPolicy: Always
      