apiVersion: v1
kind: Service
metadata:
  name: go-homework-3-core
  namespace: go
spec:
  selector:
    app: go-homework-3-core
  ports:
    - protocol: TCP
      port: 5445
      targetPort: 5445
  type: ClusterIP
  