apiVersion: v1
kind: Service
metadata:
  name: go-homework-4-nginx
  namespace: go
spec:
  selector:
    app: go-homework-4-nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
  type: ClusterIP
