apiVersion: v1
kind: Service
metadata:
  name: go-homework-3-nginx
  namespace: go
spec:
  selector:
    app: go-homework-3-nginx
  ports:
    - name: http
      protocol: TCP
      port: 80

    - name: rpc
      protocol: TCP
      port: 5445
  type: ClusterIP
