apiVersion: v1
kind: Service
metadata:
  name: go-homework-2-nginx
  namespace: go
spec:
  selector:
    app: go-homework-2-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
